### ISSUE TITLE
split cursors get out of sync when tempo changes

### ISSUE THREAD

**Issue by ianhattwick** [ijc8/cursors#16]
possibly related to #15 cursors go badly out of sync when  tempos are changed. tempos stay out of sync when tempos of multiple cursors are set to the  same value.

notably, multiple messages sent over osc at the same time have different time tags:
1. osc messages are  received in max and grouped every 5ms
2. example grouped message:
- note 0 0 3 3 0.212391 warp 1 0 3 3 0.212391 note 7 0 5 -3. 0.115238;

**Comment by ijc8** [comment]
Duplicate of #25
