### ISSUE TITLE
cursors interact with warps from different rows

### ISSUE THREAD

**Issue by ianhattwick** [ijc8/cursors#2]
Doesn't always happen but when a cursor hits a warp it will go to a warp from a diifferent row.

- the first warp must be  the cursors' rows
- the second warp can be in any row - should only be in cursors' rows

**Comment by ijc8** [comment]
Right now this should always happen, as the row of a warp is used only to determine when a cursor collides with it.
I agree that this is not what we want; warps should go to the next warp _within the cursor's vertical range_ rather than the just next warp on the board. Fix forthcoming.
